management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-service:8761/eureka
spring:
  kafka:
    bootstrap-servers: broker:29092
    consumer:
      group-id: orderId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.ecommerce.notificationservice.event.OrderPlacedEvent
  mail:
    host: smtp.gmail.com
    port: 587
    username: spshanmugapriyan641@gmail.com
    password: sdaa wecx hmpm bvxu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true